project:
  type: website
  render: 
    - "*.qmd"
    - "!files/"
  output-dir: docs
  resources: 
    - "files/" 
    - "photos/"
    - "resources/"
    - "cv/"
    - "p/"

  
website:
  title: "INQS"
  site-url: www.inqs.info
  navbar:
    right:
      - courses.qmd
      - projects.qmd
      - presentations.qmd
      - cv.qmd
      - blog.qmd
      - books.qmd
      - photos.qmd
      - icon: github
        href: https://github.com/inqs909/
        aria-label: GitHub repo
      - aria-label: R-Universe
        href: https://inqs909.r-universe.dev




format:
  html:
    theme:
      light: theme.scss
      dark: dark.scss

editor: visual

