project:
  type: website
  render: 
    - "*.qmd"
    - "!files/"
  output-dir: docs
  resources: 
    - "files/" 
    - "photos/"
    - "resources/"
    - "cv/"
    - "p/"

  
website:
  title: "INQS"
  site-url: www.inqs.info
  navbar:
    right:
      - text: "Academic"
        menu:
          - courses.qmd
          - projects.qmd
          - presentations.qmd
          - cv.qmd
      - text: "Other"
        menu:
          - blog.qmd
          - books.qmd
          - photos.qmd
      - text: "R-Universe"
        href: https://inqs909.r-universe.dev
      - icon: github
        href: https://github.com/inqs909/
        aria-label: GitHub repo





format:
  html:
    theme:
      light: theme.scss
      dark: dark.scss

editor: visual

