---
title: "Courses"
css: courses.css
editor: source
---

:::: content-block
## CSU Channel Islands

::: {.panel-tabset .nav-pills}

## AY 25-26

-   [Math 201: Elementary Statistics](https://www.inqs.info/m201_s26)

-   [Math 202: Biostatistics](https://www.inqs.info/m2012_f25)

-   [Math 352: Probability and Statistics](https://www.inqs.info/m352_f25)

-   [Math 408: Machine Learning](https://www.inqs.info/m408_s26)


-   [Math 453: Mathematical Statistics](https://www.inqs.info/m453_s26)


## AY 24-25

-   [Math 201: Elementary Statistics](https://www.inqs.info/m201_f24)

-   [Math 453: Mathematical Statistics](https://www.inqs.info/m453_f24)

-   [Math 497: Introduction to Monte Carlo Methods](https://www.inqs.info/m497_su24)

## AY 23-24

-   [Math 201: Elementary Statistics](https://www.inqs.info/m201_f23/)

-   [Math 398: Advanced Research Investigation](https://www.inqs.info/m398_f23/)

-   [Math 408: Advanced Data Analysis](inqs909.github.io/m408_s24)

## AY 22-23

-   [Math 352: Probability and Statistics](https://m352.inqs.info)

-   [Math 408: Advanced Data Analysis](https://inqs909.gitlab.io/m408_s23)

-   [Math 453: Mathematical Statistics](https://inqs909.gitlab.io/m453_f22)
:::
::::

:::: content-block
## UC Riverside

::: {.panel-tabset .nav-pills}
## All

-   STAT 127: Introduction to Quality Management

-   STAT 147: Introduction to Statistical Computing

-   STAT 100: Introduction to Statistics

-   STAT 170: Regression and ANOVA

-   STAT 048: Introduction to Business Statistics

-   UB: Math Courses

-   UB: Public Health Courses

-   UB: Research Courses

## Associate Instructor

-   STAT 127: Introduction to Quality Management

-   STAT 147: Introduction to Statistical Computing

## Teaching Assistant

-   STAT 100: Introduction to Statistics

-   STAT 170: Regression and ANOVA

-   STAT 048: Introduction to Business Statistics
:::
::::